### ISSUE TITLE
Update issue labels

### ISSUE THREAD

**Issue by lesserwhirls** [ioos/thredds-ugrid#2]
We will need to update the issue labels (e.g. "good first issue" is not particularly useful for this project, should probably add "Deliverable" as a tag, etc.)

**Comment by rsignell-usgs** [comment]
@lesserwhirls you are an admin (as are @kwilcox and @yosoyjay), so go wild!

**Comment by lesserwhirls** [comment]
Sweet - thanks @rsignell-usgs!
